### ISSUE TITLE
Does this work with Cyberark 10.10.1?

### ISSUE THREAD

**Issue by patdelaney** [AndrewCopeland/conjur-extension-azure-devops#3]
It's not clear if this will work with Cyberark 10.10.1. Here is a screenshot of the login dashboard.

![image](https://user-images.githubusercontent.com/8147459/72068702-4ebc9680-32ab-11ea-884d-ccc4ff15a47a.png)

**Comment by AndrewCopeland** [comment]
This extension only interfaces with conjur and does not touch any cyberark APIs.
